---
- name: provision service
  hosts: default
  become: yes
  become_user: 'root'

  vars:
    - service_name: "django"

    - use_nginx: True
    - use_python3: True

  roles:
    - common
    - python
    - django
